trigger: none

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "Running PR validation"
  displayName: 'Run PR Check'
- script: |
    exit 1 # Force failure
  displayName: 'Force failure'
